name: CI Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Сабиров Михаил Евгеньевич"
      GROUP_NUMBER: "М3115"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Show directory structure for debugging
        run: |
          echo "Current directory structure after checkout:"
          ls -R

      - name: Output personal information
        run: |
          echo "ФИО: $FULL_NAME"
          echo "Номер группы: $GROUP_NUMBER"
          echo "GitHub Nickname: $GITHUB_ACTOR"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Run tests
        run: |
          python -m unittest discover -s geometric_lib/unit_tests -p "*.py"  # Используем относительный путь к unit_tests

      - name: Check code style
        run: |
          pip install flake8 autopep8
          flake8 geometric_lib || (echo "Code style issues found. Attempting to auto-fix..." && autopep8 --in-place --aggressive --aggressive geometric_lib)
