name: CI Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop
      - feat/tests  # Указание, что workflow будет запускаться с ветки feat/tests

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Сабиров Михаил Евгеньевич"
      GROUP_NUMBER: "М3115"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Show directory structure for debugging
        run: |
          echo "Current directory structure after checkout:"
          ls -R  # Выводим структуру каталогов для отладки

      - name: Output personal information
        run: |
          echo "ФИО: $FULL_NAME"
          echo "Номер группы: $GROUP_NUMBER"
          echo "GitHub Nickname: $GITHUB_ACTOR"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Ensure __init__.py in unit_tests
        run: |
          if [ ! -f "geometric_lib/unit_tests/__init__.py" ]; then
            touch geometric_lib/unit_tests/__init__.py
          fi
          
      - name: Set working directory for testing
        run: |
          cd geometric_lib  # Устанавливаем правильную рабочую директорию

      - name: Run tests (discover all test files automatically)
        run: |
          # Используем unittest discover с параметрами для поиска всех тестов
          python -m unittest discover -s unit_tests -p "test_*.py"  # Автоматический поиск всех файлов с тестами, начинающихся с "test_"

      - name: Check code style
        run: |
          pip install flake8 autopep8
          flake8 geometric_lib || (echo "Code style issues found. Attempting to auto-fix..." && autopep8 --in-place --aggressive --aggressive geometric_lib)
